function make_longitudinal_QC_and_requested_analyses_NEWCOHORT_2026_v2()
% Schema-locked analysis for ALL_mice_longitudinal.csv (generated by your upstream pipeline).
% Produces BOTH QC + requested analysis:
% - Licking metrics + cumulative lick curves (0 min -> session end), day-by-day
% - Period comparisons with/without transition days (Active vs Passive, passive-day6-10 special)
% - Pupil daily + Day3 normalization
% - Event-locked pupil: reward-locked + lick-BOUT-locked (bout gap 2s), rewarded vs non-rewarded bouts
% - Assays: tail immersion, TST, hot plate, Straub (expects upstream column names)

%% ---------------- USER CONFIG ----------------
rootTry = 'K:\addiction_concate_Dec_2025\longitudinal_outputs';

% Periods (as you defined)
PER.hab      = 1:2;      % ignore
PER.pre      = 3:5;      % water PR
PER.during   = 6:10;     % passive morphine training (active has PR; passive replay/forced)
PER.post     = 11:13;    % morphine PR all
PER.withdraw = 14:16;    % withdrawal water PR
PER.reexp    = 17:18;    % re-exposure morphine PR

% Transition/less reliable days (you requested)
transitionDays = [4 6 11 14 17];

% Comparisons requested (with/without transition days is handled)
activeCompareSets  = {5, 6:10, 11:13, 14:16, 17:18};
passiveCompareSets = {5, 11:13, 14:16, 17:18};  % passive excludes 6-10 for PR-style comparisons

% Passive special pupil focus (you requested)
passiveDuringFocusDays = [7 8 9];
passivePostFocusDays   = [12 13];

% Lick bout definition (you requested)
boutGap_s     = 2.0;   % consecutive licks with gap < 2s => same bout
winPre_s      = 2.0;   % baseline window before event
winPost_s     = 2.0;   % window after event (for both start-locked and end-locked)
rewardTol_s   = 1.0;   % bout considered rewarded if any Injector_TTL within [boutStart, boutEnd+rewardTol_s]

% Time base column for traces (your pipeline produces PlotTime_s_30fps)
timeVar = 'PlotTime_s_30fps';

% Output folder name under runDir
OUT_SUBFOLDER = fullfile('figs','QC_and_requested_analyses_NEWCOHORT_2026_v2');

% Assay columns expected from upstream (STRICT names, no guessing)
ASSAY_COLS = { ...
    'Immersion_Latency_s', ...
    'TST_Frames_Nonmoving', ...
    'HOT_Frames_Nonmoving' ...
};
% Straub columns vary by your behaviorNames; we will require at least one STRAUB_* column exists
% (but we will not guess which one). You can add explicit STRAUB columns here if you want strictness:
% e.g., 'STRAUB_Pct_StraubTail' or 'STRAUB_Frames_StraubTail'
STRAUB_PREFIX = 'STRAUB_';

% For day-pair assay comparisons (like your example day5 vs day9)
assayDayPair = [5 9];
%% ---------------------------------------------------------

runDir = findLatestRunDir(rootTry);
outDir = fullfile(runDir, OUT_SUBFOLDER);
if ~exist(outDir,'dir'), mkdir(outDir); end

ts = char(datetime('now','Format','yyyyMMdd_HHmmss'));
diary(fullfile(outDir, ['runlog_' ts '.txt']));
fprintf('RunDir: %s\nOutDir: %s\n', runDir, outDir);

%% ---------------- Load combined CSV (schema-locked) ----------------
csvPath = fullfile(runDir, 'ALL_mice_longitudinal.csv');
assert(exist(csvPath,'file')==2, 'Missing %s', csvPath);

T0 = readtable(csvPath, 'VariableNamingRule','preserve');
fprintf('Loaded %s (%d rows, %d cols)\n', csvPath, height(T0), width(T0));

% REQUIRED core columns for requested analyses (strict, no guessing)
REQ = { ...
    'mouse_key','day_index','session_idx', ...
    timeVar,'Diameter_px','Lick_TTL','Injector_TTL', ...
    'TrialRequirement','Trial' ...
};
assertHasCols(T0, REQ, 'ALL_mice_longitudinal.csv');

% Cohort mapping (your new cohort info)
cohort = buildCohortTable();
T0 = joinCohortStrict(T0, cohort);

% Phase label
T0 = addPhaseLabelStrict(T0, PER);

% Remove habituation days 1-2 for most plots
Tmain = T0(~ismember(T0.day_index, PER.hab), :);

%% ---------------- QC ----------------
qc_missingness(Tmain, outDir);
qc_basic_outliers(Tmain, outDir);

%% ---------------- Build per-session summary from trace table ----------------
Sall = buildSessionSummary(Tmain, timeVar);

% Split versions: with and without transition days
S_noTrans = Sall(~ismember(Sall.day_index, transitionDays), :);

%% ---------------- Licking: day-by-day core plots ----------------
plot_lick_spaghetti_per_day(Sall, outDir, 'ALL_days');
plot_lick_spaghetti_per_day(S_noTrans, outDir, 'EXCLUDING_transition_days');

plot_pr_spaghetti_per_day(Sall, outDir, 'ALL_days');
plot_pr_spaghetti_per_day(S_noTrans, outDir, 'EXCLUDING_transition_days');

%% ---------------- Cumulative lick curves across session time (day-by-day) ----------------
% This replicates the style in your screenshots: mean cumulative licks vs time,
% with one line per day.
plot_cumulative_lick_curves_by_day(Tmain, timeVar, outDir, 'Active', 'ALL_days');
plot_cumulative_lick_curves_by_day(Tmain, timeVar, outDir, 'Passive', 'ALL_days');

% Example early vs late (days1-5 vs 6-10) for Active mice like your figure
plot_cumulative_lick_curves_two_sets(Tmain, timeVar, outDir, 'Active', 1:5, 6:10, 'Active_Early(1-5)_vs_Late(6-10)');

%% ---------------- Period comparisons (requested) ----------------
% Uses per-mouse per-period means, compares Active and Passive separately,
% with/without transition days.
period_comparisons_requested(Sall, outDir, 'ALL_days', activeCompareSets, passiveCompareSets);
period_comparisons_requested(S_noTrans, outDir, 'EXCLUDING_transition_days', activeCompareSets, passiveCompareSets);

%% ---------------- Pupil: daily + Day3 baseline normalization ----------------
plot_pupil_daily_spaghetti(Tmain, outDir, 'ALL_days');
plot_pupil_daily_spaghetti(T0(~ismember(T0.day_index, transitionDays),:), outDir, 'EXCLUDING_transition_days');

plot_pupil_day3_normalized(T0, outDir, 'ALL_days');
plot_pupil_day3_normalized(T0(~ismember(T0.day_index, transitionDays),:), outDir, 'EXCLUDING_transition_days');

%% ---------------- Event-locked pupil ----------------
% (1) Reward-locked pupil (Injector_TTL onsets)
% (2) Lick-bout-locked pupil (boutGap=2s), start-locked and end-locked
%     Separates rewarded vs non-rewarded bouts (based on Injector_TTL timing)

event_locked_pupil_all(Tmain, timeVar, outDir, ...
    winPre_s, winPost_s, boutGap_s, rewardTol_s, ...
    passiveDuringFocusDays, passivePostFocusDays, ...
    'ALL_days');

event_locked_pupil_all(T0(~ismember(T0.day_index, transitionDays),:), timeVar, outDir, ...
    winPre_s, winPost_s, boutGap_s, rewardTol_s, ...
    passiveDuringFocusDays, passivePostFocusDays, ...
    'EXCLUDING_transition_days');

%% ---------------- Assays: immersion, TST, HOT, Straub ----------------
assay_plots_and_stats(T0, outDir, ASSAY_COLS, STRAUB_PREFIX, assayDayPair, 'ALL_days');
assay_plots_and_stats(T0(~ismember(T0.day_index, transitionDays),:), outDir, ASSAY_COLS, STRAUB_PREFIX, assayDayPair, 'EXCLUDING_transition_days');

fprintf('\nDONE. Outputs saved to:\n  %s\n', outDir);
diary off;

end

%% ========================================================================
%% Helper functions (schema-locked; no guessing)
%% ========================================================================

function runDir = findLatestRunDir(rootTry)
    assert(exist(rootTry,'dir')==7, 'Root folder not found: %s', rootTry);
    D = dir(fullfile(rootTry,'run_*'));
    assert(~isempty(D), 'No run_* folder under %s', rootTry);
    [~,ix] = max([D.datenum]);
    runDir = fullfile(D(ix).folder, D(ix).name);
end

function assertHasCols(T, cols, context)
    vn = T.Properties.VariableNames;
    missing = cols(~ismember(cols, vn));
    assert(isempty(missing), 'Missing required columns in %s:\n  %s', context, strjoin(missing, ', '));
end

function cohort = buildCohortTable()
    rows = {
        "6100_red",    "F", "S";
        "6100_orange", "F", "P";
        "6100_black",  "F", "A";

        "0911_red",    "F", "A";
        "0911_orange", "F", "P";
        "0911_black",  "F", "P";
        "0911_white",  "F", "A";

        "0910_red",    "M", "P";
        "0910_orange", "M", "P";
        "0910_black",  "M", "A";

        "6099_red",    "M", "P";
        "6099_orange", "M", "A";
        "6099_black",  "M", "A";
        "6099_white",  "M", "P"; % died later; keep mapping for partial days
    };
    cohort = cell2table(rows, 'VariableNames', {'mouse_key','Sex','Group'});
end

function T = joinCohortStrict(T, cohort)
    % Strict join on mouse_key (no guessing)
    assertHasCols(T, {'mouse_key'}, 'input table');
    [tf,loc] = ismember(string(T.mouse_key), string(cohort.mouse_key));
    assert(all(tf), 'Some mouse_key values in CSV are not in cohort table. First few:\n%s', ...
        strjoin(unique(string(T.mouse_key(~tf)))(1:min(10,sum(~tf))), ', '));

    T.Sex = categorical(cohort.Sex(loc));
    T.Group = categorical(cohort.Group(loc));
    % Convenience label
    T.GroupLabel = categorical(repmat("Passive", height(T), 1));
    T.GroupLabel(T.Group=="A") = "Active";
    T.GroupLabel(T.Group=="P") = "Passive";
    T.GroupLabel(T.Group=="S") = "Special";
end

function T = addPhaseLabelStrict(T, PER)
    % Schema-locked: uses day_index
    assertHasCols(T, {'day_index'}, 'phase labeling');
    phase = repmat("other", height(T), 1);
    phase(ismember(T.day_index, PER.hab))      = "hab";
    phase(ismember(T.day_index, PER.pre))      = "pre";
    phase(ismember(T.day_index, PER.during))   = "during";
    phase(ismember(T.day_index, PER.post))     = "post";
    phase(ismember(T.day_index, PER.withdraw)) = "withdraw";
    phase(ismember(T.day_index, PER.reexp))    = "reexp";
    T.Phase = categorical(phase, ["hab","pre","during","post","withdraw","reexp","other"]);
end

function qc_missingness(T, outDir)
    % Missingness heatmap by mouse x day for core modalities
    mice = unique(string(T.mouse_key));
    days = unique(T.day_index); days = sort(days(:));
    coreCols = {'Diameter_px','Lick_TTL','Injector_TTL','TrialRequirement'};
    M = nan(numel(mice), numel(days), numel(coreCols));

    for i=1:numel(mice)
        for j=1:numel(days)
            sub = T(string(T.mouse_key)==mice(i) & T.day_index==days(j), :);
            for k=1:numel(coreCols)
                v = sub.(coreCols{k});
                M(i,j,k) = mean(isfinite(double(v)));
            end
        end
    end

    for k=1:numel(coreCols)
        f = figure('Color','w','Position',[100 100 1200 450]);
        imagesc(M(:,:,k), [0 1]); colormap(parula); colorbar;
        set(gca,'XTick',1:numel(days),'XTickLabel',days);
        set(gca,'YTick',1:numel(mice),'YTickLabel',mice);
        xlabel('Day'); ylabel('Mouse'); title(['QC missing fraction: ' coreCols{k}]);
        saveas(f, fullfile(outDir, ['QC_missing_' coreCols{k} '.png']));
        close(f);
    end
end

function qc_basic_outliers(T, outDir)
    % Simple robust outlier flags for pupil and lick counts by session
    S = buildSessionSummary(T, 'PlotTime_s_30fps');

    f = figure('Color','w','Position',[100 100 1200 420]);
    tiledlayout(1,2);

    nexttile;
    scatter(S.day_index + 0.05*randn(height(S),1), S.TotalLicks, 18, 'filled');
    xlabel('Day'); ylabel('Total licks/session'); title('QC: Total licks scatter');
    grid on;

    nexttile;
    scatter(S.day_index + 0.05*randn(height(S),1), S.MeanPupil, 18, 'filled');
    xlabel('Day'); ylabel('Mean pupil/session (px)'); title('QC: Mean pupil scatter');
    grid on;

    saveas(f, fullfile(outDir, 'QC_scatter_lick_pupil.png'));
    close(f);
end

function S = buildSessionSummary(T, timeVar)
    % Build per-session metrics from the frame-level combined CSV
    assertHasCols(T, {'mouse_key','day_index','session_idx',timeVar,'Diameter_px','Lick_TTL','Injector_TTL','TrialRequirement','Trial'}, ...
        'buildSessionSummary inputs');

    G = findgroups(string(T.mouse_key), T.day_index, T.session_idx, string(T.GroupLabel));
    mice = splitapply(@(x)x(1), string(T.mouse_key), G);
    day  = splitapply(@(x)x(1), T.day_index, G);
    sess = splitapply(@(x)x(1), T.session_idx, G);
    grp  = splitapply(@(x)x(1), string(T.GroupLabel), G);

    TotalLicks = splitapply(@(t,lk)countOnsets(t,lk), T.(timeVar), T.Lick_TTL, G);
    TotalRewards = splitapply(@(t,inj)countOnsets(t,inj), T.(timeVar), T.Injector_TTL, G);
    SessDur_s = splitapply(@(t)max(t)-min(t), T.(timeVar), G);

    MeanPupil = splitapply(@(p)mean(p(isfinite(p))), double(T.Diameter_px), G);

    % Lick frequency (licks/min)
    LickRate_per_min = TotalLicks ./ max(1e-6, (SessDur_s/60));

    % Lick IEI (period) in seconds: median inter-lick interval from lick onsets
    MedianIEI_s = splitapply(@(t,lk)medianIEI(t,lk), T.(timeVar), T.Lick_TTL, G);

    % PR score proxy: last finite TrialRequirement value in session
    RequirementLast = splitapply(@(req)lastFinite(req), double(T.TrialRequirement), G);

    S = table(mice, day, sess, categorical(grp), SessDur_s, TotalLicks, TotalRewards, ...
        LickRate_per_min, MedianIEI_s, MeanPupil, RequirementLast, ...
        'VariableNames', {'mouse_key','day_index','session_idx','GroupLabel','SessionDur_s', ...
        'TotalLicks','TotalRewards','LickRate_per_min','MedianIEI_s','MeanPupil','RequirementLast'});
end

function n = countOnsets(t, ttl)
    ttl = double(ttl); ttl(isnan(ttl)) = 0;
    x = ttl > 0.5;
    onset = x & [false; ~x(1:end-1)];
    n = sum(onset);
end

function iei = medianIEI(t, ttl)
    ttl = double(ttl); ttl(isnan(ttl)) = 0;
    x = ttl > 0.5;
    onset = x & [false; ~x(1:end-1)];
    tt = double(t(onset));
    if numel(tt) < 2
        iei = NaN;
    else
        iei = median(diff(tt));
    end
end

function v = lastFinite(x)
    x = double(x);
    idx = find(isfinite(x), 1, 'last');
    if isempty(idx), v = NaN; else, v = x(idx); end
end

function plot_lick_spaghetti_per_day(S, outDir, tag)
    % Lick count per day spaghetti (by mouse) + bold mean, Active and Passive separately
    f = figure('Color','w','Position',[100 100 1200 450]);
    tiledlayout(1,2);

    for panel = 1:2
        if panel==1, grp = "Active"; else, grp = "Passive"; end
        nexttile; hold on;
        sub = S(string(S.GroupLabel)==grp, :);
        if isempty(sub), title([grp ' (none)']); continue; end

        mice = unique(string(sub.mouse_key));
        days = unique(sub.day_index); days = sort(days(:));

        Yall = nan(numel(mice), numel(days));
        for i=1:numel(mice)
            for j=1:numel(days)
                idx = string(sub.mouse_key)==mice(i) & sub.day_index==days(j);
                if any(idx), Yall(i,j) = mean(sub.TotalLicks(idx)); end
            end
            plot(days, Yall(i,:), '-o', 'LineWidth', 1);
        end
        plot(days, nanmean(Yall,1), 'k-', 'LineWidth', 4);

        xlabel('Day index'); ylabel('Lick count per day');
        title(['Spaghetti: Lick count per day (' char(grp) ')']);
        grid on;
    end

    saveas(f, fullfile(outDir, ['LickSpaghetti_' tag '.png']));
    close(f);
end

function plot_pr_spaghetti_per_day(S, outDir, tag)
    % PR score spaghetti (RequirementLast)
    f = figure('Color','w','Position',[100 100 1200 450]);
    tiledlayout(1,2);

    for panel = 1:2
        if panel==1, grp = "Active"; else, grp = "Passive"; end
        nexttile; hold on;
        sub = S(string(S.GroupLabel)==grp, :);
        if isempty(sub), title([grp ' (none)']); continue; end

        mice = unique(string(sub.mouse_key));
        days = unique(sub.day_index); days = sort(days(:));

        Yall = nan(numel(mice), numel(days));
        for i=1:numel(mice)
            for j=1:numel(days)
                idx = string(sub.mouse_key)==mice(i) & sub.day_index==days(j);
                if any(idx), Yall(i,j) = mean(sub.RequirementLast(idx), 'omitnan'); end
            end
            plot(days, Yall(i,:), '-o', 'LineWidth', 1);
        end
        plot(days, nanmean(Yall,1), 'k-', 'LineWidth', 4);

        xlabel('Day index'); ylabel('PR score (RequirementLast)');
        title(['Spaghetti: PR score (' char(grp) ')']);
        grid on;
    end

    saveas(f, fullfile(outDir, ['PRSpaghetti_' tag '.png']));
    close(f);
end

function plot_cumulative_lick_curves_by_day(T, timeVar, outDir, groupName, tag)
    % Mean cumulative lick vs session time, with one line per day (as in your figure)
    sub = T(string(T.GroupLabel)==groupName, :);
    if isempty(sub), return; end

    days = unique(sub.day_index); days = sort(days(:));
    f = figure('Color','w','Position',[100 100 1200 450]); hold on;
    title(['Cumulative licking across session (' groupName ' mice)']);
    xlabel('Session time (min)'); ylabel('Mean cumulative licks');
    grid on;

    for d = days(:)'
        Td = sub(sub.day_index==d, :);
        if isempty(Td), continue; end

        % Build per-session cumulative curve then average across sessions
        G = findgroups(string(Td.mouse_key), Td.session_idx);
        curves = splitapply(@(t,lk)cumCurve(t,lk), Td.(timeVar), Td.Lick_TTL, G);

        % curves is cell array of [timeMinGrid, cum] but splitapply returns cell in column
        [tgrid, cm] = stackCurves(curves);
        if isempty(cm), continue; end
        plot(tgrid, mean(cm,1,'omitnan'), 'LineWidth', 2, 'DisplayName', ['Day ' num2str(d)]);
    end
    legend('Location','eastoutside');
    saveas(f, fullfile(outDir, ['CumulativeLicks_byDay_' groupName '_' tag '.png']));
    close(f);
end

function plot_cumulative_lick_curves_two_sets(T, timeVar, outDir, groupName, daysA, daysB, figTag)
    sub = T(string(T.GroupLabel)==groupName, :);
    if isempty(sub), return; end

    f = figure('Color','w','Position',[100 100 1200 450]); hold on;
    title(['Early (days ' vec2str(daysA) ') vs Late (days ' vec2str(daysB) ') sessions (' groupName ' mice)']);
    xlabel('Session time (min)'); ylabel('Mean cumulative licks');
    grid on;

    cmA = meanCumAcrossDays(sub, timeVar, daysA);
    cmB = meanCumAcrossDays(sub, timeVar, daysB);

    if ~isempty(cmA.t), plot(cmA.t, cmA.y, 'LineWidth', 3, 'DisplayName', ['Days ' vec2str(daysA)]); end
    if ~isempty(cmB.t), plot(cmB.t, cmB.y, 'LineWidth', 3, 'DisplayName', ['Days ' vec2str(daysB)]); end

    legend('Location','southeast');
    saveas(f, fullfile(outDir, ['CumulativeLicks_TwoSets_' figTag '.png']));
    close(f);
end

function out = meanCumAcrossDays(sub, timeVar, daysSet)
    Td = sub(ismember(sub.day_index, daysSet), :);
    if isempty(Td)
        out.t = []; out.y = [];
        return;
    end
    G = findgroups(string(Td.mouse_key), Td.day_index, Td.session_idx);
    curves = splitapply(@(t,lk)cumCurve(t,lk), Td.(timeVar), Td.Lick_TTL, G);
    [tgrid, cm] = stackCurves(curves);
    if isempty(cm)
        out.t = []; out.y = [];
    else
        out.t = tgrid;
        out.y = mean(cm,1,'omitnan');
    end
end

function C = cumCurve(t, lickTTL)
    t = double(t); lickTTL = double(lickTTL); lickTTL(isnan(lickTTL))=0;
    t = t - min(t); % relative
    x = lickTTL > 0.5;
    on = x & [false; ~x(1:end-1)];
    lickTimes = t(on);

    % 0..ceil(sessionMin) in 1-min bins, like your figures
    tEndMin = ceil(max(t)/60);
    tgrid = 0:1:tEndMin;
    cum = zeros(size(tgrid));
    for i=1:numel(tgrid)
        cum(i) = sum(lickTimes <= tgrid(i)*60);
    end
    C = {tgrid, cum};
end

function [tgrid, M] = stackCurves(curvesCell)
    % curvesCell: N x 1 cell, each cell is {tgrid, cum}
    if isempty(curvesCell), tgrid=[]; M=[]; return; end
    curvesCell = curvesCell(:);

    % Find max grid length
    maxLen = 0; tgrid = [];
    for i=1:numel(curvesCell)
        if isempty(curvesCell{i}), continue; end
        tg = curvesCell{i}{1};
        if numel(tg) > maxLen
            maxLen = numel(tg);
            tgrid = tg;
        end
    end
    if maxLen==0, tgrid=[]; M=[]; return; end

    M = nan(numel(curvesCell), maxLen);
    for i=1:numel(curvesCell)
        if isempty(curvesCell{i}), continue; end
        tg = curvesCell{i}{1};
        cu = curvesCell{i}{2};
        M(i,1:numel(cu)) = cu;
        % If shorter, leave trailing NaN
    end
end

function s = vec2str(v)
    v = v(:)';
    if isempty(v), s=''; return; end
    s = sprintf('%d-', v(1));
    if numel(v)==1, s = sprintf('%d', v(1)); return; end
    s = [sprintf('%d', v(1)) ':' sprintf('%d', v(end))];
end

function period_comparisons_requested(S, outDir, tag, activeSets, passiveSets)
    % Compare TotalLicks and RequirementLast across requested day-sets, per mouse mean per set.
    % Active and Passive handled separately (passive excludes during for PR by design).

    metrics = {'TotalLicks','LickRate_per_min','MedianIEI_s','MeanPupil','RequirementLast'};

    % Active
    doPeriodCompOneGroup(S, outDir, tag, "Active", activeSets, metrics);
    % Passive
    doPeriodCompOneGroup(S, outDir, tag, "Passive", passiveSets, metrics);
end

function doPeriodCompOneGroup(S, outDir, tag, groupName, daySets, metrics)
    sub = S(string(S.GroupLabel)==groupName, :);
    if isempty(sub), return; end

    mice = unique(string(sub.mouse_key));
    K = numel(daySets);

    for m = 1:numel(metrics)
        met = metrics{m};
        if ~ismember(met, sub.Properties.VariableNames), continue; end

        X = nan(numel(mice), K);
        for i=1:numel(mice)
            for k=1:K
                ds = daySets{k};
                idx = string(sub.mouse_key)==mice(i) & ismember(sub.day_index, ds);
                if any(idx)
                    X(i,k) = mean(sub.(met)(idx), 'omitnan');
                end
            end
        end

        f = figure('Color','w','Position',[100 100 1200 420]);
        boxplot(X, 'Labels', composeSetLabels(daySets));
        ylabel(met);
        title(sprintf('%s: %s period comparison (%s)', groupName, met, tag));
        grid on;

        saveas(f, fullfile(outDir, sprintf('PeriodComp_%s_%s_%s.png', groupName, met, tag)));
        close(f);

        % Save numeric table too
        Tout = array2table(X, 'VariableNames', matlab.lang.makeValidName(composeSetLabels(daySets)));
        Tout.mouse_key = mice;
        Tout = movevars(Tout, 'mouse_key', 'Before', 1);
        writetable(Tout, fullfile(outDir, sprintf('PeriodComp_%s_%s_%s.csv', groupName, met, tag)));
    end
end

function labels = composeSetLabels(daySets)
    labels = strings(1,numel(daySets));
    for k=1:numel(daySets)
        ds = daySets{k};
        if isscalar(ds)
            labels(k) = "Day" + string(ds);
        else
            labels(k) = "D" + string(min(ds)) + "_" + string(max(ds));
        end
    end
end

function plot_pupil_daily_spaghetti(T, outDir, tag)
    % Daily mean pupil by mouse, split active/passive, plus bold mean
    assertHasCols(T, {'mouse_key','day_index','Diameter_px','GroupLabel'}, 'pupil daily spaghetti');

    % Aggregate per mouse per day (mean pupil)
    G = findgroups(string(T.mouse_key), T.day_index, string(T.GroupLabel));
    mice = splitapply(@(x)x(1), string(T.mouse_key), G);
    day  = splitapply(@(x)x(1), T.day_index, G);
    grp  = splitapply(@(x)x(1), string(T.GroupLabel), G);
    mu   = splitapply(@(p)mean(p(isfinite(p))), double(T.Diameter_px), G);
    D = table(mice, day, categorical(grp), mu, 'VariableNames', {'mouse_key','day_index','GroupLabel','MeanPupil'});

    f = figure('Color','w','Position',[100 100 1200 520]);
    tiledlayout(2,1);

    for panel=1:2
        if panel==1, gname="Active"; else, gname="Passive"; end
        nexttile; hold on;
        sub = D(string(D.GroupLabel)==gname, :);
        if isempty(sub), title([gname ' (none)']); continue; end

        miceU = unique(string(sub.mouse_key));
        daysU = unique(sub.day_index); daysU = sort(daysU(:));
        Y = nan(numel(miceU), numel(daysU));

        for i=1:numel(miceU)
            for j=1:numel(daysU)
                idx = string(sub.mouse_key)==miceU(i) & sub.day_index==daysU(j);
                if any(idx), Y(i,j) = mean(sub.MeanPupil(idx),'omitnan'); end
            end
            plot(daysU, Y(i,:), '-o', 'LineWidth', 1);
        end
        plot(daysU, nanmean(Y,1), 'k-', 'LineWidth', 4);
        xlabel('Day index'); ylabel('Pupil diameter (px)');
        title(['Pupil diameter (px) - ' char(gname) ' mice']);
        grid on;
    end

    saveas(f, fullfile(outDir, ['PupilDaily_' tag '.png']));
    close(f);
end

function plot_pupil_day3_normalized(T, outDir, tag)
    % Normalize each mouse by Day3 baseline (delta from Day3 mean)
    assertHasCols(T, {'mouse_key','day_index','Diameter_px','GroupLabel'}, 'pupil day3 normalization');

    % Mean per mouse/day
    G = findgroups(string(T.mouse_key), T.day_index, string(T.GroupLabel));
    mice = splitapply(@(x)x(1), string(T.mouse_key), G);
    day  = splitapply(@(x)x(1), T.day_index, G);
    grp  = splitapply(@(x)x(1), string(T.GroupLabel), G);
    mu   = splitapply(@(p)mean(p(isfinite(p))), double(T.Diameter_px), G);
    D = table(mice, day, categorical(grp), mu, 'VariableNames', {'mouse_key','day_index','GroupLabel','MeanPupil'});

    miceU = unique(string(D.mouse_key));
    base = nan(numel(miceU),1);
    for i=1:numel(miceU)
        idx = string(D.mouse_key)==miceU(i) & D.day_index==3;
        if any(idx), base(i) = mean(D.MeanPupil(idx),'omitnan'); end
    end

    D.BaseDay3 = nan(height(D),1);
    for i=1:numel(miceU)
        D.BaseDay3(string(D.mouse_key)==miceU(i)) = base(i);
    end
    D.DeltaFromDay3 = D.MeanPupil - D.BaseDay3;

    f = figure('Color','w','Position',[100 100 1200 520]);
    tiledlayout(2,1);

    for panel=1:2
        if panel==1, gname="Active"; else, gname="Passive"; end
        nexttile; hold on;
        sub = D(string(D.GroupLabel)==gname, :);
        if isempty(sub), title([gname ' (none)']); continue; end

        miceG = unique(string(sub.mouse_key));
        daysU = unique(sub.day_index); daysU = sort(daysU(:));
        Y = nan(numel(miceG), numel(daysU));

        for i=1:numel(miceG)
            for j=1:numel(daysU)
                idx = string(sub.mouse_key)==miceG(i) & sub.day_index==daysU(j);
                if any(idx), Y(i,j) = mean(sub.DeltaFromDay3(idx),'omitnan'); end
            end
            plot(daysU, Y(i,:), '-o', 'LineWidth', 1);
        end
        plot(daysU, nanmean(Y,1), 'k-', 'LineWidth', 4);
        xlabel('Day index'); ylabel('\Delta pupil (px) vs Day3 baseline');
        title(['Day3-normalized pupil - ' char(gname) ' mice']);
        grid on;
    end

    saveas(f, fullfile(outDir, ['PupilDay3Normalized_' tag '.png']));
    close(f);
end

function event_locked_pupil_all(T, timeVar, outDir, winPre, winPost, boutGap, rewardTol, ...
                               passiveDuringDays, passivePostDays, tag)
    assertHasCols(T, {'mouse_key','day_index','session_idx',timeVar,'Diameter_px','Lick_TTL','Injector_TTL','GroupLabel'}, ...
        'event locked pupil');

    % We will produce:
    % (A) Reward-locked pupil: Active Early(pre 3-5) vs Active Late(during 7-10), Passive Early(3-5) vs Passive Late(7-10)
    % (B) Lick-BOUT-locked pupil: start-locked and end-locked, rewarded vs non-rewarded
    % (C) Passive special: days7-9 vs days12-13

    % Define default early/late sets similar to your figure
    earlyDays = [3 4 5];
    lateDays  = [7 8 9 10];

    % --- Reward-locked traces ---
    reward_locked_plot(T, timeVar, outDir, earlyDays, lateDays, winPre, winPost, tag);

    % --- Bout-locked traces (rewarded vs non-rewarded), start-locked ---
    bout_locked_plot(T, timeVar, outDir, earlyDays, lateDays, winPre, winPost, boutGap, rewardTol, 'start', tag);

    % --- Bout-locked traces, end-locked ---
    bout_locked_plot(T, timeVar, outDir, earlyDays, lateDays, winPre, winPost, boutGap, rewardTol, 'end', tag);

    % --- Passive special comparison: days7-9 vs days12-13 ---
    bout_locked_plot(T, timeVar, outDir, passiveDuringDays, passivePostDays, winPre, winPost, boutGap, rewardTol, 'start', ['PassiveFocus_' tag], "PassiveOnly");
    reward_locked_plot(T, timeVar, outDir, passiveDuringDays, passivePostDays, winPre, winPost, ['PassiveFocus_' tag], "PassiveOnly");
end

function reward_locked_plot(T, timeVar, outDir, daysA, daysB, winPre, winPost, tag, forceGroup)
    if nargin < 9, forceGroup = ""; end

    dt = 1/30; % PlotTime_s_30fps implies 30 fps
    tgrid = (-winPre:dt:winPost);

    groupsToDo = ["Active","Passive"];
    if forceGroup ~= ""
        groupsToDo = string(forceGroup);
    end

    f = figure('Color','w','Position',[100 100 1200 520]);
    tiledlayout(numel(groupsToDo),1);

    for gi=1:numel(groupsToDo)
        gname = groupsToDo(gi);
        nexttile; hold on;

        [mA, nA] = meanEventTrace(T, timeVar, gname, daysA, tgrid, 'Injector_TTL', winPre);
        [mB, nB] = meanEventTrace(T, timeVar, gname, daysB, tgrid, 'Injector_TTL', winPre);

        plot(tgrid, mA, '-', 'LineWidth', 2, 'DisplayName', sprintf('%s Days %s (n=%d)', gname, vec2str(daysA), nA));
        plot(tgrid, mB, '--', 'LineWidth', 2, 'DisplayName', sprintf('%s Days %s (n=%d)', gname, vec2str(daysB), nB));
        xline(0,'k-');

        xlabel('Time from reward (s)');
        ylabel('\Delta pupil (baseline-subtracted)');
        title(sprintf('Reward-locked pupil (%s): %s vs %s', gname, vec2str(daysA), vec2str(daysB)));
        legend('Location','best'); grid on;
    end

    saveas(f, fullfile(outDir, sprintf('RewardLockedPupil_%s.png', tag)));
    close(f);
end

function bout_locked_plot(T, timeVar, outDir, daysA, daysB, winPre, winPost, boutGap, rewardTol, lockMode, tag, forceGroup)
    if nargin < 12, forceGroup = ""; end
    dt = 1/30;
    tgrid = (-winPre:dt:winPost);

    groupsToDo = ["Active","Passive"];
    if forceGroup ~= ""
        groupsToDo = string(forceGroup);
    end

    f = figure('Color','w','Position',[100 100 1200 700]);
    tiledlayout(numel(groupsToDo),2); % rewarded vs nonrewarded

    for gi=1:numel(groupsToDo)
        gname = groupsToDo(gi);

        % rewarded
        nexttile; hold on;
        [mA, nA] = meanBoutTrace(T, timeVar, gname, daysA, tgrid, winPre, boutGap, rewardTol, true, lockMode);
        [mB, nB] = meanBoutTrace(T, timeVar, gname, daysB, tgrid, winPre, boutGap, rewardTol, true, lockMode);

        plot(tgrid, mA, '-', 'LineWidth', 2, 'DisplayName', sprintf('%s %s rewarded %s (n=%d)', gname, lockMode, vec2str(daysA), nA));
        plot(tgrid, mB, '--', 'LineWidth', 2, 'DisplayName', sprintf('%s %s rewarded %s (n=%d)', gname, lockMode, vec2str(daysB), nB));
        xline(0,'k-'); yline(0,'k:');
        xlabel(sprintf('Time from bout-%s (s)', lockMode));
        ylabel('\Delta pupil (baseline-subtracted)');
        title(sprintf('%s: Rewarded lick-bout locked (%s)', gname, lockMode));
        legend('Location','best'); grid on;

        % non-rewarded
        nexttile; hold on;
        [mA2, nA2] = meanBoutTrace(T, timeVar, gname, daysA, tgrid, winPre, boutGap, rewardTol, false, lockMode);
        [mB2, nB2] = meanBoutTrace(T, timeVar, gname, daysB, tgrid, winPre, boutGap, rewardTol, false, lockMode);

        plot(tgrid, mA2, '-', 'LineWidth', 2, 'DisplayName', sprintf('%s %s nonreward %s (n=%d)', gname, lockMode, vec2str(daysA), nA2));
        plot(tgrid, mB2, '--', 'LineWidth', 2, 'DisplayName', sprintf('%s %s nonreward %s (n=%d)', gname, lockMode, vec2str(daysB), nB2));
        xline(0,'k-'); yline(0,'k:');
        xlabel(sprintf('Time from bout-%s (s)', lockMode));
        ylabel('\Delta pupil (baseline-subtracted)');
        title(sprintf('%s: Non-rewarded lick-bout locked (%s)', gname, lockMode));
        legend('Location','best'); grid on;
    end

    saveas(f, fullfile(outDir, sprintf('BoutLockedPupil_%s_%s.png', lockMode, tag)));
    close(f);
end

function [mTrace, nEvents] = meanEventTrace(T, timeVar, groupName, daysSet, tgrid, ttlCol, winPre)
    sub = T(string(T.GroupLabel)==groupName & ismember(T.day_index, daysSet), :);
    if isempty(sub)
        mTrace = nan(size(tgrid)); nEvents = 0; return;
    end

    G = findgroups(string(sub.mouse_key), sub.day_index, sub.session_idx);
    traces = {};
    for g=1:max(G)
        Ts = sub(G==g,:);
        t = double(Ts.(timeVar)); p = double(Ts.Diameter_px);
        ttl = double(Ts.(ttlCol)); ttl(isnan(ttl))=0;
        x = ttl>0.5; on = x & [false; ~x(1:end-1)];
        ev = t(on);
        if isempty(ev), continue; end

        for e=1:numel(ev)
            tr = extractDeltaPupil(t, p, ev(e), tgrid, winPre);
            if any(isfinite(tr)), traces{end+1,1} = tr; end %#ok<AGROW>
        end
    end

    if isempty(traces)
        mTrace = nan(size(tgrid)); nEvents = 0; return;
    end

    M = cell2mat(traces);
    mTrace = mean(M, 1, 'omitnan');
    nEvents = size(M,1);
end

function [mTrace, nBouts] = meanBoutTrace(T, timeVar, groupName, daysSet, tgrid, winPre, boutGap, rewardTol, wantRewarded, lockMode)
    sub = T(string(T.GroupLabel)==groupName & ismember(T.day_index, daysSet), :);
    if isempty(sub)
        mTrace = nan(size(tgrid)); nBouts = 0; return;
    end

    G = findgroups(string(sub.mouse_key), sub.day_index, sub.session_idx);
    traces = {};
    for g=1:max(G)
        Ts = sub(G==g,:);
        t = double(Ts.(timeVar)); p = double(Ts.Diameter_px);

        % lick onsets
        lk = double(Ts.Lick_TTL); lk(isnan(lk))=0;
        x = lk>0.5; on = x & [false; ~x(1:end-1)];
        lickTimes = t(on);
        if numel(lickTimes) < 1, continue; end

        % reward onsets
        inj = double(Ts.Injector_TTL); inj(isnan(inj))=0;
        xi = inj>0.5; oni = xi & [false; ~xi(1:end-1)];
        rewardTimes = t(oni);

        % build bouts
        [bStart, bEnd] = buildBouts(lickTimes, boutGap);

        for b=1:numel(bStart)
            isRew = any(rewardTimes >= bStart(b) & rewardTimes <= (bEnd(b)+rewardTol));
            if isRew ~= wantRewarded, continue; end

            if strcmpi(lockMode,'start')
                ev = bStart(b);
            else
                ev = bEnd(b);
            end
            tr = extractDeltaPupil(t, p, ev, tgrid, winPre);
            if any(isfinite(tr)), traces{end+1,1} = tr; end %#ok<AGROW>
        end
    end

    if isempty(traces)
        mTrace = nan(size(tgrid)); nBouts = 0; return;
    end

    M = cell2mat(traces);
    mTrace = mean(M, 1, 'omitnan');
    nBouts = size(M,1);
end

function [bStart, bEnd] = buildBouts(lickTimes, gap_s)
    lickTimes = sort(lickTimes(:));
    if isempty(lickTimes)
        bStart = []; bEnd = []; return;
    end
    d = [inf; diff(lickTimes)];
    newBout = d > gap_s;
    idxStart = find(newBout);
    idxEnd = [idxStart(2:end)-1; numel(lickTimes)];
    bStart = lickTimes(idxStart);
    bEnd   = lickTimes(idxEnd);
end

function tr = extractDeltaPupil(t, p, ev, tgrid, winPre)
    % Baseline is mean in [-winPre, 0) relative to event
    rel = t - ev;
    % interpolate pupil onto tgrid
    tr0 = interp1(rel, p, tgrid, 'linear', NaN);

    baseMask = (tgrid >= -winPre) & (tgrid < 0);
    baseVal = mean(tr0(baseMask), 'omitnan');
    tr = tr0 - baseVal;
end

function assay_plots_and_stats(T, outDir, assayCols, straubPrefix, dayPair, tag)
    % Strict expected assay columns (except Straub where we require at least one STRAUB_* column exists)
    assertHasCols(T, {'mouse_key','day_index','GroupLabel'}, 'assay plots');

    % Build per-mouse per-day scalar table (take first finite value per mouse/day)
    % This assumes assay columns are repeated across frames; upstream pipeline does that.
    mice = unique(string(T.mouse_key));
    days = unique(T.day_index); days = sort(days(:));

    % Check assay columns exist (strict)
    for i=1:numel(assayCols)
        assertHasCols(T, assayCols(i), 'assay columns');
    end

    % Straub: require at least one column starting with STRAUB_
    vn = string(T.Properties.VariableNames);
    straubCols = vn(startsWith(vn, straubPrefix));
    assert(~isempty(straubCols), 'No Straub columns found. Expected at least one column starting with "%s".', straubPrefix);

    % We will plot each required assay + a summary Straub plot of the first STRAUB_* column
    allCols = [string(assayCols(:)); straubCols(1)];

    for c = 1:numel(allCols)
        col = char(allCols(c));

        % Aggregate mean per mouse/day (first finite)
        D = nan(numel(mice), numel(days));
        G = strings(numel(mice),1); % group label per mouse from cohort mapping
        for i=1:numel(mice)
            Gi = unique(string(T.GroupLabel(string(T.mouse_key)==mice(i))));
            if ~isempty(Gi), G(i) = Gi(1); else, G(i) = "Unknown"; end
            for j=1:numel(days)
                sub = T(string(T.mouse_key)==mice(i) & T.day_index==days(j), :);
                v = double(sub.(col));
                v = v(isfinite(v));
                if ~isempty(v), D(i,j) = v(1); end
            end
        end

        % Line plot: active vs passive mean by day
        f = figure('Color','w','Position',[100 100 1200 420]); hold on;
        idxA = (G=="Active"); idxP = (G=="Passive");
        plot(days, nanmean(D(idxA,:),1), '-o', 'LineWidth', 3, 'DisplayName','Active');
        plot(days, nanmean(D(idxP,:),1), '-o', 'LineWidth', 3, 'DisplayName','Passive');
        xlabel('Day index'); ylabel(col);
        title(sprintf('%s: Active vs Passive means per day', col));
        legend('Location','best'); grid on;
        saveas(f, fullfile(outDir, sprintf('Assay_Line_%s_%s.png', col, tag)));
        close(f);

        % Day-pair boxplot (like your Day5 vs Day9 style)
        d1 = dayPair(1); d2 = dayPair(2);
        y = [D(idxA, days==d1); D(idxP, days==d1); D(idxA, days==d2); D(idxP, days==d2)];
        gLabel = [ ...
            repmat("Day"+d1+"_Active", sum(idxA),1);
            repmat("Day"+d1+"_Passive",sum(idxP),1);
            repmat("Day"+d2+"_Active", sum(idxA),1);
            repmat("Day"+d2+"_Passive",sum(idxP),1)
        ];
        f2 = figure('Color','w','Position',[100 100 900 520]);
        boxplot(y, gLabel);
        ylabel(col);
        title(sprintf('%s: 4-group comparison (Day%d vs Day%d)', col, d1, d2));
        grid on;
        saveas(f2, fullfile(outDir, sprintf('Assay_Box_%s_Day%d_Day%d_%s.png', col, d1, d2, tag)));
        close(f2);
    end
end
