function make_longitudinal_QC_and_requested_analyses_NEWCOHORT_2026_FINAL()
% Schema-strict QC + requested analyses for NEW COHORT / NEW TIMELINE.
%
% INPUT:  ALL_mice_longitudinal.csv generated by:
%   Longitudinal_final_trialrequire_HOTTST_passive_final_handle_nomatchingstrabu.m
%
% OUTPUT: figures + CSV summaries under:
%   <latest run_*/QC_AND_REQUESTED_ANALYSES_<timestamp>/>
%
% IMPORTANT: This script does NOT guess schema.
% It REQUIRES specific column names and errors clearly if missing.

%% ===================== USER CONFIG =====================
cfg = struct();

% Root
cfg.rootTry = 'K:\addiction_concate_Dec_2025\longitudinal_outputs';

% Days
cfg.ignoreDays      = [1 2];              % habituation
cfg.transitionDays  = [4 6 11 14 17];      % “less reliable” (edit if you want)

% Timeline phases (fixed)
cfg.phaseNames = ["PRE","DURING","POST","WITHDRAWAL","REEXPOSURE"];

% Phase day ranges
cfg.phaseDays.PRE        = 3:5;
cfg.phaseDays.DURING     = 6:10;
cfg.phaseDays.POST       = 11:13;
cfg.phaseDays.WITHDRAWAL = 14:16;
cfg.phaseDays.REEXPOSURE = 17:18;

% Pupil normalization baseline day (per mouse)
cfg.pupilBaselineDay = 3;

% Lick bout definition
cfg.boutGapSec  = 2.0;

% Event-lock window (seconds)
cfg.winPre  = 2.0;
cfg.winPost = 2.0;
cfg.fsTimeForEventLock = 30; % because PlotTime_s_30fps implies ~30 fps sampling

% Cumulative lick curve bins
cfg.sessionMaxMin = 20;      % you can increase if sessions are longer
cfg.binWidthSec   = 60;      % 1-minute bins for cumulative curves

% Comparisons requested
cfg.activeCompareDays = struct( ...
    'PRE_last',        5, ...
    'DURING',          6:10, ...
    'POST',            11:13, ...
    'WITHDRAWAL',      14:16, ...
    'REEXPOSURE_first',17);

cfg.passiveCompareDays = struct( ...
    'PRE_last',        5, ...
    'POST',            11:13, ...
    'WITHDRAWAL',      14:16, ...
    'REEXPOSURE',      17:18);

cfg.passiveFocusDays = 6:10;     % passive morphine training days
cfg.passiveVsActive_days_789 = 7:9;
cfg.passiveVsActive_days_1213 = 12:13;

%% ===================== COHORT METADATA =====================
C = cohortTable_NEWCOHORT_2026(); % strict mapping (mouse_key_norm, sex, isPassive, pair_id)

%% ===================== LOCATE LATEST RUN + CSV =====================
[rootOK, runDir] = findLatestRunDir(cfg.rootTry);
if ~rootOK
    error('Cannot find longitudinal_outputs. Update cfg.rootTry.');
end

csvPath = findFileRecursiveNewest(runDir, 'ALL_mice_longitudinal.csv');
if isempty(csvPath)
    error('Could not find ALL_mice_longitudinal.csv under: %s', runDir);
end

ts = char(datetime('now','Format','yyyyMMdd_HHmmss'));
outDir = fullfile(runDir, ['QC_AND_REQUESTED_ANALYSES_' ts]);
if ~exist(outDir,'dir'), mkdir(outDir); end

fprintf('\nUsing runDir:\n  %s\n', runDir);
fprintf('Reading CSV:\n  %s\n', csvPath);
fprintf('Saving outputs to:\n  %s\n\n', outDir);

%% ===================== READ + STRICT SCHEMA CHECK =====================
T = readtable(csvPath, 'VariableNamingRule','preserve');

% Required columns for licking + pupil pipeline
req = { ...
    'mouse_key', 'day_index', 'session_idx', ...
    'PlotTime_s_30fps', 'Lick_TTL', 'Reward_TTL', ...
    'Diameter_px' ...
    };

assertHasVars(T, req, 'Core lick/pupil analysis');

% Optional but strongly expected for PR
hasPR = ismember('TrialRequirement', T.Properties.VariableNames);

% Ensure types
T.mouse_key  = string(T.mouse_key);
T.day_index  = double(T.day_index);
T.session_idx = double(T.session_idx);

% Merge cohort metadata (strict)
T.mouse_key_norm = lower(strrep(strtrim(T.mouse_key)," ",""));
T = outerjoin(T, C, 'Keys','mouse_key_norm','MergeKeys',true,'Type','left');
if any(ismissing(T.isPassive))
    missingKeys = unique(T.mouse_key_norm(ismissing(T.isPassive)));
    fprintf('\nWARNING: Some mouse_key not found in cohort table:\n');
    disp(missingKeys);
    fprintf('They will be kept but excluded from group comparisons.\n\n');
end

% Remove habituation days (global)
T = T(~ismember(T.day_index, cfg.ignoreDays), :);

% Build two variants: include vs exclude transition days
variants = { ...
    struct('name',"INCLUDE_TRANSITIONS",'excludeTransitions',false), ...
    struct('name',"EXCLUDE_TRANSITIONS",'excludeTransitions',true) ...
    };

for v = 1:numel(variants)
    V = variants{v};
    vDir = fullfile(outDir, char(V.name));
    if ~exist(vDir,'dir'), mkdir(vDir); end

    fprintf('=== Variant: %s ===\n', V.name);

    Tuse = T;
    if V.excludeTransitions
        Tuse = Tuse(~ismember(Tuse.day_index, cfg.transitionDays), :);
    end

    % Make phase labels (strict day->phase mapping)
    Tuse.phase = strings(height(Tuse),1);
    Tuse.phase(:) = "NONE";
    Tuse.phase(ismember(Tuse.day_index, cfg.phaseDays.PRE))        = "PRE";
    Tuse.phase(ismember(Tuse.day_index, cfg.phaseDays.DURING))     = "DURING";
    Tuse.phase(ismember(Tuse.day_index, cfg.phaseDays.POST))       = "POST";
    Tuse.phase(ismember(Tuse.day_index, cfg.phaseDays.WITHDRAWAL)) = "WITHDRAWAL";
    Tuse.phase(ismember(Tuse.day_index, cfg.phaseDays.REEXPOSURE)) = "REEXPOSURE";
    Tuse.phase = string(Tuse.phase);

    % ===================== QC TABLES =====================
    qcDir = fullfile(vDir,'QC');
    if ~exist(qcDir,'dir'), mkdir(qcDir); end

    [Sess, Day] = buildSessionAndDayTables(Tuse, hasPR);

    writetable(Sess, fullfile(qcDir,'session_table.csv'));
    writetable(Day,  fullfile(qcDir,'day_table.csv'));

    doQCplots(Sess, Day, qcDir);

    % ===================== LICKING ANALYSES =====================
    lickDir = fullfile(vDir,'LICKING');
    if ~exist(lickDir,'dir'), mkdir(lickDir); end

    doLickSpaghettiPlots(Day, lickDir);                  % lick count / lick rate across days
    doCumulativeLickCurvesByDay(Tuse, lickDir, cfg);     % day-by-day cumulative licking curves
    doEarlyLateCumulative(Tuse, lickDir, cfg);           % early vs late (3-5 vs 6-10) by group

    % Period comparisons requested (active vs passive rules differ)
    periodDir = fullfile(vDir,'PERIOD_COMPARISONS');
    if ~exist(periodDir,'dir'), mkdir(periodDir); end
    doRequestedPeriodComparisons(Day, periodDir, cfg);

    % ===================== PR SCORE (if present) =====================
    if hasPR
        prDir = fullfile(vDir,'PR');
        if ~exist(prDir,'dir'), mkdir(prDir); end
        doPRplots(Day, prDir);
    else
        fprintf('NOTE: TrialRequirement column not present; PR plots skipped.\n');
    end

    % ===================== PUPIL ANALYSES =====================
    pupilDir = fullfile(vDir,'PUPIL');
    if ~exist(pupilDir,'dir'), mkdir(pupilDir); end

    doPupilDayByDayNormalized(Day, pupilDir, cfg);         % normalize to day3 per mouse
    doPupilMorphineVsWaterBoxes(Day, pupilDir, cfg);       % day4-5 vs day12-13 style comparisons

    % Event-locked pupil (reward-locked + lick-bout-locked)
    eventDir = fullfile(vDir,'PUPIL_EVENT_LOCKED');
    if ~exist(eventDir,'dir'), mkdir(eventDir); end
    doEventLockedPupil(Tuse, eventDir, cfg);

    % Special passive focus comparisons
    doPassiveFocusComparisons(Day, pupilDir, cfg);

    % ===================== NON-LICK ASSAYS (if present) =====================
    assayDir = fullfile(vDir,'ASSAYS');
    if ~exist(assayDir,'dir'), mkdir(assayDir); end
    doAssayPlotsAndStats(Tuse, assayDir);

    fprintf('Done variant: %s\n\n', V.name);
end

fprintf('ALL DONE. Outputs at:\n  %s\n', outDir);

end

%% =====================================================================
%% ===================== CORE TABLE BUILDERS ============================
function [Sess, Day] = buildSessionAndDayTables(T, hasPR)
% Session table: one row per mouse-day-session
% Day table: one row per mouse-day (average across sessions)

% Build lick/reward edges at the frame level per session
G = findgroups(T.mouse_key_norm, T.day_index, T.session_idx);

Sess = table();
Sess.mouse_key_norm = splitapply(@(x)x(1), T.mouse_key_norm, G);
Sess.mouse_key      = splitapply(@(x)x(1), string(T.mouse_key), G);
Sess.day_index      = splitapply(@(x)x(1), T.day_index, G);
Sess.session_idx    = splitapply(@(x)x(1), T.session_idx, G);
Sess.phase          = splitapply(@(x)x(1), string(T.phase), G);
Sess.isPassive      = splitapply(@(x)x(1), T.isPassive, G);
Sess.sex            = splitapply(@(x)x(1), string(T.sex), G);
Sess.pair_id        = splitapply(@(x)x(1), string(T.pair_id), G);

% Time
tmin = splitapply(@(x)min(x), T.PlotTime_s_30fps, G);
tmax = splitapply(@(x)max(x), T.PlotTime_s_30fps, G);
Sess.session_dur_s = tmax - tmin;
Sess.session_dur_min = Sess.session_dur_s / 60;

% Lick count (rising edges of Lick_TTL)
Sess.lick_count = splitapply(@(x)countRises(x), T.Lick_TTL, G);
Sess.reward_count = splitapply(@(x)countRises(x), T.Reward_TTL, G);

Sess.licks_per_min = Sess.lick_count ./ max(1e-6, Sess.session_dur_min);

% IEI (lick period) metrics
Sess.iei_mean_s = splitapply(@(tt,lk)ieiMean(tt,lk), T.PlotTime_s_30fps, T.Lick_TTL, G);
Sess.iei_cv     = splitapply(@(tt,lk)ieiCV(tt,lk),   T.PlotTime_s_30fps, T.Lick_TTL, G);

% Pupil mean per session
Sess.pupil_mean_px = splitapply(@(x)nanmean(x), T.Diameter_px, G);

% PR score per session if possible
if hasPR
    Sess.PR_requirement_last = splitapply(@(x)prLast(x), T.TrialRequirement, G);
else
    Sess.PR_requirement_last = nan(height(Sess),1);
end

% Day table: average over sessions per mouse-day
Gd = findgroups(Sess.mouse_key_norm, Sess.day_index);

Day = table();
Day.mouse_key_norm = splitapply(@(x)x(1), Sess.mouse_key_norm, Gd);
Day.mouse_key      = splitapply(@(x)x(1), Sess.mouse_key, Gd);
Day.day_index      = splitapply(@(x)x(1), Sess.day_index, Gd);
Day.phase          = splitapply(@(x)x(1), Sess.phase, Gd);
Day.isPassive      = splitapply(@(x)x(1), Sess.isPassive, Gd);
Day.sex            = splitapply(@(x)x(1), Sess.sex, Gd);
Day.pair_id        = splitapply(@(x)x(1), Sess.pair_id, Gd);

Day.n_sessions     = splitapply(@numel, Sess.session_idx, Gd);

Day.lick_count     = splitapply(@nanmean, Sess.lick_count, Gd);
Day.licks_per_min  = splitapply(@nanmean, Sess.licks_per_min, Gd);
Day.iei_mean_s     = splitapply(@nanmean, Sess.iei_mean_s, Gd);
Day.iei_cv         = splitapply(@nanmean, Sess.iei_cv, Gd);
Day.reward_count   = splitapply(@nanmean, Sess.reward_count, Gd);

Day.pupil_mean_px  = splitapply(@nanmean, Sess.pupil_mean_px, Gd);
Day.PR_requirement_last = splitapply(@nanmean, Sess.PR_requirement_last, Gd);

end

%% =====================================================================
%% ===================== QC PLOTS ======================================
function doQCplots(Sess, Day, outDir)

% Coverage: sessions per mouse
f = figure('Color','w','Position',[60 60 1100 420]);
tiledlayout(1,2,'Padding','compact','TileSpacing','compact');

nexttile;
cats = categorical(Day.mouse_key_norm);
counts = groupsummary(Day,'mouse_key_norm','numel','day_index');
bar(counts.numel_day_index);
set(gca,'XTick',1:height(counts),'XTickLabel',counts.mouse_key_norm,'XTickLabelRotation',45);
ylabel('Days present'); title('Coverage per mouse (days)');
grid on;

nexttile;
histogram(Sess.session_dur_min, 30);
xlabel('Session duration (min)'); ylabel('Count'); title('Session duration distribution');
grid on;

exportgraphics(f, fullfile(outDir,'QC_coverage_and_duration.png'), 'Resolution',300);
close(f);

% Outlier scan: lick_count and pupil_mean
f = figure('Color','w','Position',[60 60 1100 420]);
tiledlayout(1,2,'Padding','compact','TileSpacing','compact');

nexttile;
histogram(Day.lick_count, 30);
xlabel('Mean lick count/day'); ylabel('Mouse-days'); title('Lick count distribution');
grid on;

nexttile;
histogram(Day.pupil_mean_px, 30);
xlabel('Mean pupil diameter (px)'); ylabel('Mouse-days'); title('Pupil mean distribution');
grid on;

exportgraphics(f, fullfile(outDir,'QC_distributions_lick_pupil.png'), 'Resolution',300);
close(f);

writetable(Day, fullfile(outDir,'QC_day_table.csv'));
writetable(Sess, fullfile(outDir,'QC_session_table.csv'));

end

%% =====================================================================
%% ===================== LICKING: SPAGHETTI =============================
function doLickSpaghettiPlots(Day, outDir)

% Active vs passive spaghetti for lick_count across days
f = figure('Color','w','Position',[60 60 1200 500]);
tiledlayout(1,2,'Padding','compact','TileSpacing','compact');

% ACTIVE
nexttile; hold on;
A = Day(Day.isPassive==0,:);
plotSpaghettiByMouse(A.day_index, A.lick_count, A.mouse_key_norm);
plotMeanBold(A.day_index, A.lick_count);
xlabel('Day'); ylabel('Lick count/day'); title('Spaghetti: Lick count per day (Active)');
grid on;

% PASSIVE
nexttile; hold on;
P = Day(Day.isPassive==1,:);
plotSpaghettiByMouse(P.day_index, P.lick_count, P.mouse_key_norm);
plotMeanBold(P.day_index, P.lick_count);
xlabel('Day'); ylabel('Lick count/day'); title('Spaghetti: Lick count per day (Passive)');
grid on;

exportgraphics(f, fullfile(outDir,'Spaghetti_lick_count_active_vs_passive.png'), 'Resolution',300);
close(f);

% IEI mean (lick period proxy)
f = figure('Color','w','Position',[60 60 1200 500]);
tiledlayout(1,2,'Padding','compact','TileSpacing','compact');

nexttile; hold on;
plotSpaghettiByMouse(A.day_index, A.iei_mean_s, A.mouse_key_norm);
plotMeanBold(A.day_index, A.iei_mean_s);
xlabel('Day'); ylabel('Mean IEI (s)'); title('Spaghetti: Mean IEI (Active)');
grid on;

nexttile; hold on;
plotSpaghettiByMouse(P.day_index, P.iei_mean_s, P.mouse_key_norm);
plotMeanBold(P.day_index, P.iei_mean_s);
xlabel('Day'); ylabel('Mean IEI (s)'); title('Spaghetti: Mean IEI (Passive)');
grid on;

exportgraphics(f, fullfile(outDir,'Spaghetti_meanIEI_active_vs_passive.png'), 'Resolution',300);
close(f);

end

%% =====================================================================
%% ===================== LICKING: CUMULATIVE CURVES =====================
function doCumulativeLickCurvesByDay(T, outDir, cfg)
% Produce day-by-day cumulative lick curves across session time.
% Similar to your attached "Cumulative licking across session".

edges = 0:cfg.binWidthSec:(cfg.sessionMaxMin*60);
binCenters = edges(1:end-1) + cfg.binWidthSec/2;

% Session list
Gsess = findgroups(T.mouse_key_norm, T.day_index, T.session_idx, T.isPassive);
sessKeys = splitapply(@(mk,dy,si,g) string(mk(1))+"|"+dy(1)+"|"+si(1)+"|"+g(1), ...
    T.mouse_key_norm, T.day_index, T.session_idx, T.isPassive, Gsess);
sessKeys = unique(sessKeys);

% Build per-session cumulative curves
S = table();
S.key = sessKeys;
S.isPassive = nan(numel(sessKeys),1);
S.day_index = nan(numel(sessKeys),1);
S.cum = nan(numel(sessKeys), numel(binCenters));

for i=1:numel(sessKeys)
    parts = split(sessKeys(i),"|");
    mk = parts(1);
    dy = str2double(parts(2));
    si = str2double(parts(3));
    gp = str2double(parts(4));

    idx = (T.mouse_key_norm==mk) & (T.day_index==dy) & (T.session_idx==si) & (T.isPassive==gp);
    if ~any(idx), continue; end

    tt = T.PlotTime_s_30fps(idx);
    lk = T.Lick_TTL(idx);

    lickTimes = eventTimesFromTTL(tt, lk);
    cumCounts = zeros(1,numel(binCenters));
    for b=1:numel(binCenters)
        cumCounts(b) = sum(lickTimes <= edges(b+1));
    end

    S.isPassive(i) = gp;
    S.day_index(i) = dy;
    S.cum(i,:) = cumCounts;
end

% Plot per day separately for Active and Passive
daysAll = unique(S.day_index(~isnan(S.day_index)));
daysAll = sort(daysAll);

% Active
f = figure('Color','w','Position',[60 60 1400 600]); hold on;
for d = daysAll'
    Sd = S(S.isPassive==0 & S.day_index==d,:);
    if isempty(Sd), continue; end
    mu = nanmean(Sd.cum,1);
    plot(binCenters/60, mu, 'LineWidth', 2);
end
xlabel('Session time (min)'); ylabel('Mean cumulative licks'); title('Cumulative licking across session (Active)');
grid on;
legend(compose("Day %d", daysAll), 'Location','eastoutside');
exportgraphics(f, fullfile(outDir,'Cumulative_licking_by_day_ACTIVE.png'), 'Resolution',300);
close(f);

% Passive
f = figure('Color','w','Position',[60 60 1400 600]); hold on;
for d = daysAll'
    Sd = S(S.isPassive==1 & S.day_index==d,:);
    if isempty(Sd), continue; end
    mu = nanmean(Sd.cum,1);
    plot(binCenters/60, mu, 'LineWidth', 2);
end
xlabel('Session time (min)'); ylabel('Mean cumulative licks'); title('Cumulative licking across session (Passive)');
grid on;
legend(compose("Day %d", daysAll), 'Location','eastoutside');
exportgraphics(f, fullfile(outDir,'Cumulative_licking_by_day_PASSIVE.png'), 'Resolution',300);
close(f);

end

function doEarlyLateCumulative(T, outDir, cfg)
% Recreate your “Early vs Late sessions” type plot, but consistent with your paradigm:
% early = days 3–5, late = days 6–10 (for licking; PR differs by group).

edges = 0:cfg.binWidthSec:(cfg.sessionMaxMin*60);
binCenters = edges(1:end-1) + cfg.binWidthSec/2;

earlyDays = cfg.phaseDays.PRE;        % 3–5
lateDays  = cfg.phaseDays.DURING;     % 6–10

for gp = [0 1]
    label = tern(gp==0,'ACTIVE','PASSIVE');

    curvesEarly = collectCumCurves(T, gp, earlyDays, edges);
    curvesLate  = collectCumCurves(T, gp, lateDays,  edges);

    if isempty(curvesEarly) || isempty(curvesLate)
        continue;
    end

    muE = mean(curvesEarly,1,'omitnan');
    muL = mean(curvesLate, 1,'omitnan');

    f = figure('Color','w','Position',[60 60 1100 500]); hold on;
    plot(binCenters/60, muE, 'LineWidth', 3);
    plot(binCenters/60, muL, 'LineWidth', 3);
    xlabel('Session time (min)'); ylabel('Mean cumulative licks');
    title(sprintf('Early (days 3–5) vs Late (days 6–10) cumulative licking (%s)', label));
    grid on; legend({'Days 3–5','Days 6–10'}, 'Location','southeast');

    exportgraphics(f, fullfile(outDir, sprintf('Early_vs_Late_Cumulative_%s.png',label)), 'Resolution',300);
    close(f);
end

end

function M = collectCumCurves(T, isPassive, days, edges)
binCenters = edges(1:end-1) + (edges(2)-edges(1))/2;

% session list
rows = T(T.isPassive==isPassive & ismember(T.day_index, days), :);
if isempty(rows), M = []; return; end

G = findgroups(rows.mouse_key_norm, rows.day_index, rows.session_idx);
nSess = max(G);
M = nan(nSess, numel(binCenters));

for s = 1:nSess
    idx = (G==s);
    tt = rows.PlotTime_s_30fps(idx);
    lk = rows.Lick_TTL(idx);
    lickTimes = eventTimesFromTTL(tt, lk);
    cumCounts = zeros(1,numel(binCenters));
    for b=1:numel(binCenters)
        cumCounts(b) = sum(lickTimes <= edges(b+1));
    end
    M(s,:) = cumCounts;
end

end

%% =====================================================================
%% ===================== PERIOD COMPARISONS REQUESTED ===================
function doRequestedPeriodComparisons(Day, outDir, cfg)

% Active comparisons (your specific day sets)
A = Day(Day.isPassive==0,:);
P = Day(Day.isPassive==1,:);

% ACTIVE: day5 vs (6-10) vs (11-13) vs (14-16) vs day17
namesA = string(fieldnames(cfg.activeCompareDays));
valsA  = cell(numel(namesA),1);
for i=1:numel(namesA)
    dset = cfg.activeCompareDays.(namesA(i));
    valsA{i} = perMouseMeanOverDays(A, dset, 'lick_count');
end
plotPeriodBoxes(valsA, namesA, 'Lick count', 'Active: requested day blocks', fullfile(outDir,'Active_requested_blocks_lickcount.png'));

% PASSIVE: day5 vs (11-13) vs (14-16) vs (17-18)
namesP = string(fieldnames(cfg.passiveCompareDays));
valsP  = cell(numel(namesP),1);
for i=1:numel(namesP)
    dset = cfg.passiveCompareDays.(namesP(i));
    valsP{i} = perMouseMeanOverDays(P, dset, 'lick_count');
end
plotPeriodBoxes(valsP, namesP, 'Lick count', 'Passive: requested day blocks', fullfile(outDir,'Passive_requested_blocks_lickcount.png'));

% Also lick rate and IEI mean (lick period)
valsA = cell(numel(namesA),1);
for i=1:numel(namesA), valsA{i} = perMouseMeanOverDays(A, cfg.activeCompareDays.(namesA(i)), 'licks_per_min'); end
plotPeriodBoxes(valsA, namesA, 'Licks/min', 'Active: requested day blocks', fullfile(outDir,'Active_requested_blocks_lickrate.png'));

valsP = cell(numel(namesP),1);
for i=1:numel(namesP), valsP{i} = perMouseMeanOverDays(P, cfg.passiveCompareDays.(namesP(i)), 'licks_per_min'); end
plotPeriodBoxes(valsP, namesP, 'Licks/min', 'Passive: requested day blocks', fullfile(outDir,'Passive_requested_blocks_lickrate.png'));

valsA = cell(numel(namesA),1);
for i=1:numel(namesA), valsA{i} = perMouseMeanOverDays(A, cfg.activeCompareDays.(namesA(i)), 'iei_mean_s'); end
plotPeriodBoxes(valsA, namesA, 'Mean IEI (s)', 'Active: requested day blocks', fullfile(outDir,'Active_requested_blocks_IEI.png'));

valsP = cell(numel(namesP),1);
for i=1:numel(namesP), valsP{i} = perMouseMeanOverDays(P, cfg.passiveCompareDays.(namesP(i)), 'iei_mean_s'); end
plotPeriodBoxes(valsP, namesP, 'Mean IEI (s)', 'Passive: requested day blocks', fullfile(outDir,'Passive_requested_blocks_IEI.png'));

end

function V = perMouseMeanOverDays(D, days, varname)
% returns one value per mouse (mean over specified days)
Dd = D(ismember(D.day_index, days), :);
if isempty(Dd)
    V = [];
    return;
end
G = findgroups(Dd.mouse_key_norm);
V = splitapply(@(x)nanmean(x), Dd.(varname), G);
end

function plotPeriodBoxes(valsCell, labels, ylab, ttl, savePath)
f = figure('Color','w','Position',[60 60 1200 500]);
data = []; grp = [];
for i=1:numel(valsCell)
    v = valsCell{i};
    data = [data; v(:)];
    grp  = [grp; repmat(i, numel(v), 1)];
end
boxchart(grp, data);
set(gca,'XTick',1:numel(labels),'XTickLabel',labels);
ylabel(ylab); title(ttl); grid on;
exportgraphics(f, savePath, 'Resolution',300);
close(f);
end

%% =====================================================================
%% ===================== PR PLOTS =======================================
function doPRplots(Day, outDir)

f = figure('Color','w','Position',[60 60 1200 500]);
tiledlayout(1,2,'Padding','compact','TileSpacing','compact');

A = Day(Day.isPassive==0,:);
P = Day(Day.isPassive==1,:);

nexttile; hold on;
plotSpaghettiByMouse(A.day_index, A.PR_requirement_last, A.mouse_key_norm);
plotMeanBold(A.day_index, A.PR_requirement_last);
xlabel('Day'); ylabel('PR score (RequirementLast)'); title('Spaghetti: PR score (Active)');
grid on;

nexttile; hold on;
plotSpaghettiByMouse(P.day_index, P.PR_requirement_last, P.mouse_key_norm);
plotMeanBold(P.day_index, P.PR_requirement_last);
xlabel('Day'); ylabel('PR score (RequirementLast)'); title('Spaghetti: PR score (Passive)');
grid on;

exportgraphics(f, fullfile(outDir,'Spaghetti_PR_active_vs_passive.png'), 'Resolution',300);
close(f);

end

%% =====================================================================
%% ===================== PUPIL: DAY-BY-DAY NORMALIZED ===================
function doPupilDayByDayNormalized(Day, outDir, cfg)

% baseline per mouse = day3 mean pupil
base = Day(Day.day_index==cfg.pupilBaselineDay, {'mouse_key_norm','pupil_mean_px'});
base = rmmissing(base);

D = Day;
D.pupil_norm_to_day3 = nan(height(D),1);

% map
m = containers.Map(base.mouse_key_norm, base.pupil_mean_px);
for i=1:height(D)
    key = D.mouse_key_norm(i);
    if isKey(m, key) && ~isnan(D.pupil_mean_px(i))
        b = m(key);
        D.pupil_norm_to_day3(i) = (D.pupil_mean_px(i) - b) ./ max(1e-6,b);
    end
end

% Plot active vs passive normalized
f = figure('Color','w','Position',[60 60 1200 500]);
tiledlayout(2,1,'Padding','compact','TileSpacing','compact');

A = D(D.isPassive==0,:);
P = D(D.isPassive==1,:);

nexttile; hold on;
plotSpaghettiByMouse(A.day_index, A.pupil_norm_to_day3, A.mouse_key_norm);
plotMeanBold(A.day_index, A.pupil_norm_to_day3);
xlabel('Day'); ylabel('\Delta pupil / baseline(day3)'); title('Pupil normalized to day3 baseline (Active)');
grid on;

nexttile; hold on;
plotSpaghettiByMouse(P.day_index, P.pupil_norm_to_day3, P.mouse_key_norm);
plotMeanBold(P.day_index, P.pupil_norm_to_day3);
xlabel('Day'); ylabel('\Delta pupil / baseline(day3)'); title('Pupil normalized to day3 baseline (Passive)');
grid on;

exportgraphics(f, fullfile(outDir,'Pupil_normalized_to_day3_active_vs_passive.png'), 'Resolution',300);
close(f);

writetable(D, fullfile(outDir,'DayTable_with_pupil_norm_to_day3.csv'));

end

function doPupilMorphineVsWaterBoxes(Day, outDir, cfg)
% Requested: compare pupil morphine vs water using day3 as baseline.
% Practical choice:
% - Water-ish: days 4-5 (PRE late)
% - Morphine PR: days 12-13 (POST)

tblPath = fullfile(outDir,'DayTable_with_pupil_norm_to_day3.csv');
if ~exist(tblPath,'file')
    return;
end
D = readtable(tblPath);
D.mouse_key_norm = string(D.mouse_key_norm);

waterDays = [4 5];
morphDays = [12 13];

A = D(D.isPassive==0,:);
P = D(D.isPassive==1,:);

Aw = perMouseMeanOverDays(A, waterDays, 'pupil_norm_to_day3');
Am = perMouseMeanOverDays(A, morphDays, 'pupil_norm_to_day3');
Pw = perMouseMeanOverDays(P, waterDays, 'pupil_norm_to_day3');
Pm = perMouseMeanOverDays(P, morphDays, 'pupil_norm_to_day3');

f = figure('Color','w','Position',[60 60 1100 500]); hold on;
data = [Aw(:); Pw(:); Am(:); Pm(:)];
grp  = [repmat("Water_Active",numel(Aw),1); repmat("Water_Passive",numel(Pw),1); ...
        repmat("Morph_Active",numel(Am),1); repmat("Morph_Passive",numel(Pm),1)];
boxchart(categorical(grp), data);
ylabel('\Delta pupil / baseline(day3)'); title('Pupil: Water (days4-5) vs Morphine (days12-13), normalized to day3');
grid on;
exportgraphics(f, fullfile(outDir,'Pupil_Water_vs_Morphine_box.png'), 'Resolution',300);
close(f);

end

%% =====================================================================
%% ===================== PUPIL: EVENT-LOCKED ============================
function doEventLockedPupil(T, outDir, cfg)
% Reward-locked pupil (±2s) baseline = [-2,0)
% Lick-bout-locked pupil (bout gap = 2s) baseline = [-2,0)
% Lick bouts separated into reward-causing vs non-reward bouts

% Build event-locked averages by group and by day-blocks of interest:
% - Active early (3-5) vs during (6-10)
% - Passive early (3-5) vs during (6-10) [forced reward period]
% plus a global (all days combined) per group

blocks = struct();
blocks(1).name = "Early_3to5"; blocks(1).days = 3:5;
blocks(2).name = "During_6to10"; blocks(2).days = 6:10;
blocks(3).name = "Post_11to13"; blocks(3).days = 11:13;

for gp = [0 1]
    gLabel = tern(gp==0,'Active','Passive');

    % Reward-locked
    for b = 1:numel(blocks)
        days = blocks(b).days;
        [tvec, mu] = eventLockedMean(T, gp, days, cfg, "reward");
        if ~isempty(mu)
            f = figure('Color','w','Position',[60 60 900 500]);
            plot(tvec, mu, 'LineWidth',3);
            xlabel('Time from event (s)'); ylabel('\Delta pupil (baseline-subtracted)');
            title(sprintf('Reward-locked pupil (%s) — %s (days %s)', gLabel, blocks(b).name, num2str(days)));
            grid on;
            exportgraphics(f, fullfile(outDir, sprintf('RewardLocked_%s_%s.png', gLabel, blocks(b).name)), 'Resolution',300);
            close(f);
        end
    end

    % Lick-bout-locked (reward-causing vs non-reward)
    for b = 1:numel(blocks)
        days = blocks(b).days;

        [tvec, muR] = eventLockedMean(T, gp, days, cfg, "lickbout_reward");
        [~,   muN] = eventLockedMean(T, gp, days, cfg, "lickbout_noreward");

        if ~isempty(muR) || ~isempty(muN)
            f = figure('Color','w','Position',[60 60 900 500]); hold on;
            if ~isempty(muR), plot(tvec, muR, 'LineWidth',3); end
            if ~isempty(muN), plot(tvec, muN, '--', 'LineWidth',3); end
            xlabel('Time from event (s)'); ylabel('\Delta pupil (baseline-subtracted)');
            title(sprintf('Lick-bout-locked pupil (%s) — %s', gLabel, blocks(b).name));
            grid on;
            legendEntries = {};
            if ~isempty(muR), legendEntries{end+1} = 'Reward-causing bouts'; end %#ok<AGROW>
            if ~isempty(muN), legendEntries{end+1} = 'Non-reward bouts'; end %#ok<AGROW>
            if ~isempty(legendEntries), legend(legendEntries,'Location','best'); end
            exportgraphics(f, fullfile(outDir, sprintf('LickBoutLocked_%s_%s.png', gLabel, blocks(b).name)), 'Resolution',300);
            close(f);
        end
    end
end

end

function [tvec, mu] = eventLockedMean(T, isPassive, days, cfg, mode)
% mode:
%  "reward"             : reward rising edges
%  "lickbout_reward"    : lick-bout onset where a reward occurs within 2s after onset
%  "lickbout_noreward"  : lick-bout onset where no reward occurs within 2s after onset

rows = T(T.isPassive==isPassive & ismember(T.day_index, days), :);
if isempty(rows)
    tvec = []; mu = []; return;
end

tvec = (-cfg.winPre : 1/cfg.fsTimeForEventLock : cfg.winPost)';
snips = [];

G = findgroups(rows.mouse_key_norm, rows.day_index, rows.session_idx);
nSess = max(G);

for s = 1:nSess
    idx = (G==s);
    tt = rows.PlotTime_s_30fps(idx);
    pup = rows.Diameter_px(idx);
    lk  = rows.Lick_TTL(idx);
    rw  = rows.Reward_TTL(idx);

    % drop NaN pupil
    ok = ~isnan(tt) & ~isnan(pup);
    tt = tt(ok); pup = pup(ok); lk = lk(ok); rw = rw(ok);

    if numel(tt) < 10, continue; end

    switch mode
        case "reward"
            ev = eventTimesFromTTL(tt, rw);

        case "lickbout_reward"
            ev = lickBoutOnsets(tt, lk, cfg.boutGapSec);
            ev = ev( boutHasReward(tt, rw, ev, 2.0) );

        case "lickbout_noreward"
            ev = lickBoutOnsets(tt, lk, cfg.boutGapSec);
            ev = ev( ~boutHasReward(tt, rw, ev, 2.0) );

        otherwise
            error('Unknown mode: %s', mode);
    end

    for e = 1:numel(ev)
        t0 = ev(e);
        % baseline window [-winPre, 0)
        baseMask = (tt >= (t0-cfg.winPre)) & (tt < t0);
        if nnz(baseMask) < 5, continue; end
        base = mean(pup(baseMask), 'omitnan');

        % sample onto fixed tvec
        tq = t0 + tvec;
        pq = interp1(tt, pup, tq, 'linear', nan);
        pq = pq - base;

        if nnz(~isnan(pq)) > 0.7*numel(pq)
            snips(:, end+1) = pq; %#ok<AGROW>
        end
    end
end

if isempty(snips)
    mu = [];
else
    mu = mean(snips, 2, 'omitnan');
end

end

function onsets = lickBoutOnsets(tt, lkTTL, gapSec)
lickTimes = eventTimesFromTTL(tt, lkTTL);
if isempty(lickTimes), onsets = []; return; end
d = [inf; diff(lickTimes(:))];
starts = lickTimes(d >= gapSec);
onsets = starts(:);
end

function tf = boutHasReward(tt, rwTTL, boutOnsets, winSec)
rTimes = eventTimesFromTTL(tt, rwTTL);
tf = false(size(boutOnsets));
if isempty(rTimes), return; end
for i=1:numel(boutOnsets)
    tf(i) = any(rTimes >= boutOnsets(i) & rTimes <= (boutOnsets(i)+winSec));
end
end

%% =====================================================================
%% ===================== PASSIVE FOCUS COMPARISONS ======================
function doPassiveFocusComparisons(Day, outDir, cfg)
% Requested: passive-only focus days 7-8-9 vs 12-13, and passive vs active on those blocks.

P = Day(Day.isPassive==1,:);
A = Day(Day.isPassive==0,:);

% Passive day7-9 vs day12-13: pupil and licking
p1 = perMouseMeanOverDays(P, cfg.passiveVsActive_days_789, 'pupil_mean_px');
p2 = perMouseMeanOverDays(P, cfg.passiveVsActive_days_1213, 'pupil_mean_px');

f = figure('Color','w','Position',[60 60 900 450]);
boxchart(categorical([repmat("Passive_days7-9",numel(p1),1); repmat("Passive_days12-13",numel(p2),1)]), [p1(:); p2(:)]);
ylabel('Pupil mean (px)'); title('Passive pupil: days 7–9 vs days 12–13');
grid on;
exportgraphics(f, fullfile(outDir,'Passive_pupil_days7-9_vs_12-13_box.png'), 'Resolution',300);
close(f);

l1 = perMouseMeanOverDays(P, cfg.passiveVsActive_days_789, 'lick_count');
l2 = perMouseMeanOverDays(P, cfg.passiveVsActive_days_1213, 'lick_count');

f = figure('Color','w','Position',[60 60 900 450]);
boxchart(categorical([repmat("Passive_days7-9",numel(l1),1); repmat("Passive_days12-13",numel(l2),1)]), [l1(:); l2(:)]);
ylabel('Lick count/day'); title('Passive licking: days 7–9 vs days 12–13');
grid on;
exportgraphics(f, fullfile(outDir,'Passive_lick_days7-9_vs_12-13_box.png'), 'Resolution',300);
close(f);

% Passive vs Active on days 7-9
pP = perMouseMeanOverDays(P, cfg.passiveVsActive_days_789, 'pupil_mean_px');
pA = perMouseMeanOverDays(A, cfg.passiveVsActive_days_789, 'pupil_mean_px');
f = figure('Color','w','Position',[60 60 900 450]);
boxchart(categorical([repmat("Active_days7-9",numel(pA),1); repmat("Passive_days7-9",numel(pP),1)]), [pA(:); pP(:)]);
ylabel('Pupil mean (px)'); title('Pupil: Active vs Passive (days 7–9)');
grid on;
exportgraphics(f, fullfile(outDir,'Pupil_Active_vs_Passive_days7-9_box.png'), 'Resolution',300);
close(f);

end

%% =====================================================================
%% ===================== ASSAYS: TST / HOT / IMMERSION / STRAUB =========
function doAssayPlotsAndStats(T, outDir)
% These are expected to be present in ALL_mice_longitudinal.csv if you merged them:
%   Immersion_Latency_s
%   HOT_Frames_Nonmoving
%   TST_Frames_Nonmoving
%   Straub (varies by your manual scoring export)
%
% This function:
% - Extracts one value per mouse-day (unique non-NaN)
% - Plots Active vs Passive means per day (if multiple days)
% - Makes 4-group boxplots for day5/day9 when available (as in your examples)

varsToTry = { ...
    'Immersion_Latency_s', ...
    'HOT_Frames_Nonmoving', ...
    'TST_Frames_Nonmoving' ...
    };

% Straub variable name(s) can differ depending on manual scoring table.
% Add common candidates here WITHOUT guessing columns beyond this list:
straubCandidates = { ...
    'Straub_Score', 'StraubTail_Score', 'Straub', 'StraubTail' ...
    };

allVars = [varsToTry, straubCandidates];

for i=1:numel(allVars)
    vn = allVars{i};
    if ~ismember(vn, T.Properties.VariableNames)
        continue;
    end

    D = extractOneValuePerMouseDay(T, vn);
    if isempty(D), continue; end

    % Active vs passive means per day
    f = figure('Color','w','Position',[60 60 1000 450]); hold on;
    days = unique(D.day_index); days = sort(days);
    muA = nan(size(days)); muP = nan(size(days));
    for d=1:numel(days)
        dd = days(d);
        muA(d) = mean(D.value(D.day_index==dd & D.isPassive==0), 'omitnan');
        muP(d) = mean(D.value(D.day_index==dd & D.isPassive==1), 'omitnan');
    end
    plot(days, muA, '-o', 'LineWidth',2);
    plot(days, muP, '-o', 'LineWidth',2);
    xlabel('Day'); ylabel(vn); title(sprintf('%s: Active vs Passive means per day', vn));
    grid on; legend({'Active','Passive'},'Location','best');
    exportgraphics(f, fullfile(outDir, sprintf('%s_means_per_day.png',vn)), 'Resolution',300);
    close(f);

    % 4-group day5/day9 style boxplot (if those days exist)
    if any(days==5) && any(days==9)
        v5A = D.value(D.day_index==5 & D.isPassive==0);
        v5P = D.value(D.day_index==5 & D.isPassive==1);
        v9A = D.value(D.day_index==9 & D.isPassive==0);
        v9P = D.value(D.day_index==9 & D.isPassive==1);

        f = figure('Color','w','Position',[60 60 1000 450]);
        data = [v5A(:); v5P(:); v9A(:); v9P(:)];
        grp  = [repmat("Day5_Active",numel(v5A),1); repmat("Day5_Passive",numel(v5P),1); ...
                repmat("Day9_Active",numel(v9A),1); repmat("Day9_Passive",numel(v9P),1)];
        boxchart(categorical(grp), data);
        ylabel(vn); title(sprintf('%s: Day5/Day9 Active/Passive boxplot', vn));
        grid on;
        exportgraphics(f, fullfile(outDir, sprintf('%s_box_day5_day9.png',vn)), 'Resolution',300);
        close(f);
    end

    writetable(D, fullfile(outDir, sprintf('%s_oneValuePerMouseDay.csv',vn)));
end

end

function D = extractOneValuePerMouseDay(T, varname)
% Take unique non-NaN value per mouse-day (if multiple, take nanmean).
G = findgroups(T.mouse_key_norm, T.day_index);
mk = splitapply(@(x)x(1), T.mouse_key_norm, G);
dy = splitapply(@(x)x(1), T.day_index, G);
gp = splitapply(@(x)x(1), T.isPassive, G);
val = splitapply(@(x)nanmean(x), T.(varname), G);

D = table(string(mk), dy, gp, val, 'VariableNames',{'mouse_key_norm','day_index','isPassive','value'});
D = D(~isnan(D.value), :);
end

%% =====================================================================
%% ===================== COHORT TABLE ==================================
function C = cohortTable_NEWCOHORT_2026()
% STRICT cohort mapping based on your message.
%
% Canonical format: "cage_color" lowercase.
% Pairing:
% 1) 6100: black(active) vs orange,red(passive)
% 2) 0911: red(active) vs orange(passive)
% 3) 0911: white(active) vs black(passive)
% 4) 0910: black(active) vs orange,red(passive)
% 5) 6099: orange(active) vs red(passive)
% 6) 6099: black(active) vs white(passive)  [white died day1–13 only]

mouse_key_norm = [
    "6100_red"
    "6100_orange"
    "6100_black"
    "0911_red"
    "0911_orange"
    "0911_black"
    "0911_white"
    "0910_red"
    "0910_orange"
    "0910_black"
    "6099_red"
    "6099_orange"
    "6099_black"
    "6099_white"
    ];

% Sex (from your list; for ones not explicitly stated, keep as string but still strict)
sex = [
    "f"  % 6100_red  (you wrote f_s, but this mouse is passive in pairing)
    "f"  % 6100_orange
    "f"  % 6100_black
    "f"  % 0911_red
    "f"  % 0911_orange
    "f"  % 0911_black
    "f"  % 0911_white
    "m"  % 0910_red
    "m"  % 0910_orange
    "m"  % 0910_black
    "m"  % 6099_red
    "m"  % 6099_orange
    "m"  % 6099_black
    "m"  % 6099_white (dead day1–13)
    ];

% isPassive: 0=active, 1=passive
isPassive = [
    1  % 6100_red    passive
    1  % 6100_orange passive
    0  % 6100_black  active
    0  % 0911_red    active
    1  % 0911_orange passive
    1  % 0911_black  passive
    0  % 0911_white  active
    1  % 0910_red    passive
    1  % 0910_orange passive
    0  % 0910_black  active
    1  % 6099_red    passive
    0  % 6099_orange active
    0  % 6099_black  active
    1  % 6099_white  passive (dead early)
    ];

pair_id = [
    "6100_pair1"
    "6100_pair1"
    "6100_pair1"
    "0911_pair2"
    "0911_pair2"
    "0911_pair3"
    "0911_pair3"
    "0910_pair4"
    "0910_pair4"
    "0910_pair4"
    "6099_pair5"
    "6099_pair5"
    "6099_pair6"
    "6099_pair6"
    ];

C = table(mouse_key_norm, sex, isPassive, pair_id);

end

%% =====================================================================
%% ===================== UTILITIES =====================================
function assertHasVars(T, vars, context)
missing = vars(~ismember(vars, T.Properties.VariableNames));
if ~isempty(missing)
    fprintf('\nSCHEMA ERROR in %s.\nMissing required columns:\n', context);
    disp(missing(:));
    error('Fix CSV schema or update required variable list in the script.');
end
end

function [ok, runDir] = findLatestRunDir(rootTry)
ok = false; runDir = "";

tryPath = rootTry;
if ~exist(tryPath,'dir')
    here = pwd; cand = here;
    for up=1:6
        p = fullfile(cand,'longitudinal_outputs');
        if exist(p,'dir'), tryPath = p; break; end
        cand = fileparts(cand);
    end
end
if ~exist(tryPath,'dir'), return; end

d = dir(fullfile(tryPath,'run_*'));
if isempty(d), return; end
[~,idx] = max([d.datenum]);
runDir = fullfile(d(idx).folder, d(idx).name);
ok = true;
end

function fp = findFileRecursiveNewest(rootDir, fileName)
d = dir(fullfile(rootDir, '**', fileName));
if isempty(d), fp = ""; return; end
[~,ix] = max([d.datenum]);
fp = fullfile(d(ix).folder, d(ix).name);
end

function n = countRises(ttl)
x = double(ttl(:) > 0.5);
n = sum(diff([0; x])==1);
end

function times = eventTimesFromTTL(tt, ttl)
x = double(ttl(:) > 0.5);
r = find(diff([0; x])==1);
times = tt(r);
times = times(~isnan(times));
end

function m = ieiMean(tt, lkTTL)
lickTimes = eventTimesFromTTL(tt, lkTTL);
if numel(lickTimes) < 2, m = nan; return; end
d = diff(lickTimes);
m = mean(d,'omitnan');
end

function c = ieiCV(tt, lkTTL)
lickTimes = eventTimesFromTTL(tt, lkTTL);
if numel(lickTimes) < 3, c = nan; return; end
d = diff(lickTimes);
mu = mean(d,'omitnan');
sd = std(d,'omitnan');
c = sd / max(1e-6, mu);
end

function v = prLast(x)
% TrialRequirement may be per-frame/per-trial; we take the last non-NaN value.
x = x(:);
x = x(~isnan(x));
if isempty(x), v = nan; else, v = x(end); end
end

function plotSpaghettiByMouse(xDay, yVal, mouseKeys)
keys = unique(mouseKeys);
for i=1:numel(keys)
    idx = mouseKeys==keys(i);
    xd = xDay(idx); yd = yVal(idx);
    [xd,ord] = sort(xd); yd = yd(ord);
    plot(xd, yd, '-o', 'LineWidth',1.2, 'MarkerSize',4);
end
end

function plotMeanBold(xDay, yVal)
days = unique(xDay); days = sort(days);
mu = nan(size(days));
for i=1:numel(days)
    mu(i) = mean(yVal(xDay==days(i)), 'omitnan');
end
plot(days, mu, '-k', 'LineWidth',3);
end

function s = tern(cond, a, b)
if cond, s = a; else, s = b; end
end
